### ISSUE TITLE
Custom words not always properly lowercased when added in a custom dictionary

### ISSUE THREAD

**Issue by GilShoshan94** [streetsidesoftware/vscode-spell-checker#1048]
Hi,
Thank you for this amazing spell checker.

I understand from the README.md that the dictionaries should be entirely in lower case.
**"This spellchecker is case insensitive. It will not catch errors like english which should be English."**

---
I have a single root workspace and this is my config (in : "${workspaceFolder}/.vscode/settings.json")
```jsonc
{
    "cSpell.customWorkspaceDictionaries": [
        {
            "name": "mydictionary",
            "description": "Words used in my projects",
            "addWords": true,
            "path": "${workspaceFolder}/.vscode/mydictionary.txt"
        }
    ],
    "cSpell.dictionaries": ["mydictionary"]
}
```

Here is my custom dictionary:
![image](https://user-images.githubusercontent.com/29143941/125769808-3b84b62b-986f-4657-9d4c-4567a79ce3fc.png)

I wrote an example code:
![image](https://user-images.githubusercontent.com/29143941/125769881-23a3ea3d-9f5b-4c7c-b343-01c9b212c0b4.png)

---
Now I have two way I know off to add the new words into mydictionary.txt:
1) Via the context menu and chose `"Add Word to Workspace Dictionary"`.
2) Via the command `ctrl .` over a misspelled word and choose `"Add: "foo" to workspace dictionary"`.

Via the context menu
---
I can use the context menu and right click on the new word:
<img src="https://user-images.githubusercontent.com/29143941/125770200-1cad456d-a35c-4809-8dab-0f155d006e61.png" height=600px>

I then click on `"Add Word to Workspace Dictionary"` and get a palette to add the word, and the word is prefilled:
(By the way, I think that if the user is with the cursor on the word, and I see that you are detecting that since the palette get prefilled automatically, the word should be added immediately and that there is no need for a confirmation. But that can be another issue):
![image](https://user-images.githubusercontent.com/29143941/125770458-f04e6a63-6932-4ba4-986c-8c9ca70dd25b.png)

Then the new word get correctly inserted into the custom dictionary. It got lowercase first and it is smartly inserted according to the alphabetical order (I guess it improved performance when checking that the list is sorted).
![image](https://user-images.githubusercontent.com/29143941/125774435-41ef6248-8435-4ce1-bc03-86eed71d7c93.png)
So far so good.

Via the command `ctrl .`
---
I do `ctrl .` over a misspelled word and choose `"Add: "foo" to workspace dictionary"`:
![image](https://user-images.githubusercontent.com/29143941/125774627-0697d020-e9c2-4b84-8d2b-7b6aae1dc0e1.png)

And once I confirm (click 'enter') the word get inserted but was not lowercased first, and since capital letter comes first in the sort, it is not inserted in the right spot neither.
![image](https://user-images.githubusercontent.com/29143941/125774918-bf828b65-df5c-45ec-b57e-963c73e694ce.png)

---
So it is just a small error, you just need to apply the lowercase as well when a word is added with the command `ctrl .`

**Comment by GilShoshan94** [comment]
By the way, it is not only with a custom dictionary. I also happens with a `cspell.json` or in the `settings.json`.

**Comment by Jason3S** [comment]
@GilShoshan94,

Thank you for the detailed report. The behavior is inconsistent between the context menu and the `ctrl .`. This should be fixed in the next major update of the extension.

The `ctrl .` behavior is the one used moving forward. Dictionaries are case sensitive, so the spell checker tries to preserve the case. It cannot know if the word should be capitalized or not, so it just preserves what it was given. When editing a case insensitive file type, then lower case versions of the word will be accepted.

Please try out v2 of the spell checker: [Releases · vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases). The right click menu and `ctrl .` options have changed. Your feedback would be welcome.

**Comment by GilShoshan94** [comment]
@Jason3S 

I just tested the v2.0.1-alpha.6 as you requested me to and wrote you my result in #1049.

Now, about the capitalization, on the principle, I don't really understand your answer:

> Dictionaries are case sensitive, so the spell checker tries to preserve the case.

Ha ok dictionaries are case sensitive. Why is that if the spellchecker is case insensitive ? Isn't it easier to just save everything in lowercase ? It 's good performance wise also I think. Because you avoid storing two word that are equivalent in the eyes of the spell checker, like 'Foo' and 'foo'. Also it means that somewhere in the code that perform the comparison, you need to do something like ` lower_case(input) == lower_case(dictionary)` instead of just `lower_case(input) == dictionary`, which can improve performance.

> It cannot know if the word should be capitalized or not, so it just preserves what it was given.

Ok, why not simply lower case it anyway? When do we need the capitalized version ?

>  When editing a case insensitive file type, then lower case versions of the word will be accepted.

I don't understand. Is Code Spell Checker case sensitive now ? Is it a new feature ?
If so, can you explain what exactly it imply ? Is it just the first letter or is 'foO' different then 'Foo', 'fOo' and 'foo'.
Sounds like it could augment the dictionary size immensely and affect performance because much more check needs to apply.

**Comment by Jason3S** [comment]
@GilShoshan94,

The spell checker supports case sensitive checking. It can be enabled per file type.

The following configuration will turn on case sensitivity for `markdown` files.
```js
"languageSettings": [
    {
        "languageId": "markdown",
        "caseSensitive": true
    }
]
```

This will make it possible to correctly check proper names where case is important. This is important for LaTeX files and Markdown used for blogs and websites.

Because the spell checker was originally case intensive, making it case aware takes care so as to not break things. The first step is to upgrade to CSpell 5.x. The next step is to update the bundled and extension dictionaries at the same time keeping the default checks to be case insensitive, while allowing users to opt into turning on case sensitivity on a case by case basis.

Dictionaries are optimized for searching and generating suggestions while minimizing on their size. When a custom dictionary (word list) is loaded, it is internally optimized. The number of words in a dictionary have no impact on the search time. It is the length of the word that makes a difference.

Searches are more like: `input in dictionary || lower_case(input) in dictionary`. It is a bit more involved because the word splitter must be able to handle both `ERRORCode` and `ERRORcode`.

You are right that when a custom dictionary is loaded, there will be effectively multiple copies of the same word. It will have both `Foo` and `foo`. This is done for lookup speed. 

For example:
`Orléans` in France will have 3 copies:

```
Orléans
~orléans
~orleans
```

Where `~` tells the spell checker it that case and possibly accents were removed.

Custom dictionaries tend to be very small compared to full language dictionaries, so, they are not optimized for size.

Custom dictionaries support a few special characters:

- `~` - prefix that tells the spell checker to only use the word when case sensitivity is turned off.
- `+` - prefix/suffix that tells the spell checker that a word MUST be combined with another word to be valid.
- `*` - prefix/suffix that tells the spell checker that a word can be combined with another word.
- `!` - prefix forbid a word.

If you have the following in your custom dictionary:

```
fooo+
+baar
+bat
+cat
big*
!fooocat
```

Then `fooobaar` and `fooobat` will be valid, but `fooo`, `baar`, and `fooocat` will not be.

This is useful for languages where people commonly combine words: errorcode, systemtime, systemerror.

Note: the custom dictionary also allows other characters like: `_`, `-`, `0-9`, `'`.

Dictionary entries like:
```
systemerror-409
503_serviceunavailable
```

Will only match the entire entry: `503_serviceunavailable` but not `serviceunavailable`.

**Comment by GilShoshan94** [comment]
@Jason3S 

Thank you for the detailed explanation !
This is super interesting.

**Comment by GilShoshan94** [comment]
> @GilShoshan94,
> 
> Thank you for the detailed report. The behavior is inconsistent between the context menu and the `ctrl .`. This should be fixed in the next major update of the extension.
> ...

@Jason3S, do you want to keep this issue open until the next major update resolve it or do you want me to close it ?

**Comment by Jason3S** [comment]
Good point. I'll close it with the V2 release.

**Comment by Jason3S** [comment]
I'm closing this as done in V2.
