### ISSUE TITLE
Toggle for Global shorcut does not work after clicking the cspeller tab on the status bar

### ISSUE THREAD

**Issue by anandinasu** [streetsidesoftware/vscode-spell-checker#1289]
If the Cspell is toggled off globally, to toggle it back there are two options. Either use shortcut ("cSpell.toggleEnableForGlobal") or click on the status bar. The shortcut works totally fine until you click the icon on the status bar. Once you click it, from there onwards, toggling for global shortcut does not work anymore. The only way to make it work after clicking on the status bar for the first time is to uninstall the extension, delete the folder from .vscode folder and re-install it. However, toggling for the workspace ("cSpell.toggleEnableSpellChecker") works fine even after clicking on the status bar.

**Comment by Jason3S** [comment]
Thank you. I'll investigate.

**Comment by Jason3S** [comment]
That must be frustrating.

I'm struggling to reproduce the behavior you are experiencing.

Let me describe what I am seeing:

- Open a folder in VS Code.
- Looks like this:
    ![image](https://user-images.githubusercontent.com/3740137/133033703-f3de336c-c0f2-4d8f-bcb7-2d5cd490d36a.png)
- I open the README and it has a few issues: 
    ![image](https://user-images.githubusercontent.com/3740137/133033834-ca7aea60-1f87-4662-bbe0-94c33613a17d.png)
- I have bound some Keyboard Shortcuts
    ![image](https://user-images.githubusercontent.com/3740137/133034071-2ea6aa03-6c85-48dd-9e4a-8564eba47aef.png)
- I `Toggle Spell Checking`
    ![image](https://user-images.githubusercontent.com/3740137/133034308-04648d02-0798-4db1-a847-f6ef2d8c05ca.png)
- I can toggle it on and off.
- When it is off, I click:
    ![image](https://user-images.githubusercontent.com/3740137/133034308-04648d02-0798-4db1-a847-f6ef2d8c05ca.png)
- A new folder appears in my workspace:
    ![image](https://user-images.githubusercontent.com/3740137/133034715-d4e69ec5-fda9-4344-82c0-6d975785908a.png)
    This is where VS Code puts its workspace settings.
- If I toggle the Spell Checker, it no longer seems to work. But toggling it using the workspace command does.
- If I open another VS Code Window
    ![image](https://user-images.githubusercontent.com/3740137/133035316-777970ae-6f58-4ddb-abc9-d20f70413fa7.png)
- And open a different folder (not in the same workspace), one that does not contain a `.vscode` folder.
- Toggling the Spell Checker works.
- If I go back to the original VS Code window and open `.vscode/settings.json`
     ![image](https://user-images.githubusercontent.com/3740137/133035867-ae91a394-097f-4df5-b10a-d2c917e68ff5.png)
- Remove the line `"cSpell.enable": true` and save.
    ![image](https://user-images.githubusercontent.com/3740137/133036095-50965b20-1646-4c74-baae-625ce2436014.png)
- Now toggling works again.


Please see if these steps work for you.

In the last major release, there were a couple of behavior changes:
1. The status bar button changed to default to the `workspace` instead of the global settings.
2. The Global Toggle no longer changes workspace settings, it only changes the global settings.

I think it is these two changes that you are seeing.

**Comment by anandinasu** [comment]
Dear @Jason3S , I am so sorry. I somehow missed your response. I will try it again and update you asap. Thanks a lot for your time.

**Comment by Jason3S** [comment]
The issue gets close automatically when a fix is added to the code.

A new version of the Spell Checker should be released today or tomorrow with the fix.

**Comment by anandinasu** [comment]
Okay then I will wait for the update, retest it and update you.

**Comment by anandinasu** [comment]
Hello @Jason3S 

I got the update, I tried it again and the issue I mentioned above is fixed and the shortcut is functioning properly. However, I have a doubt regarding the changes in the settings file. When we set ```"command": "cSpell.toggleEnableForGlobal"``` isn't the changed settings supposed to be added/ changed in the user settings instead of workspace settings? If that is the case, it is working fine as long we use the shortcut for toggling. But once we click the button on the status bar, there is a different behavior and later it goes back to normal behavior. Have a look at this video. First I am showing the normal behavior, then the different behavior, and again the normal behavior.

![Screenshot_2021_09_21-15_56_50_827](https://user-images.githubusercontent.com/12847193/134134780-42cf1665-8428-4393-ba93-a47f79fafd4f.gif)

Is this how it is supposed to be? This is not an issue and is not affecting the workflow at all. I was just curious. Thank You.

**Comment by Jason3S** [comment]
I forget about the `statusbar` it should change the global setting, not the workspace setting.

**Comment by Jason3S** [comment]
In any case, the command only toggles the nearest configuration.

**Comment by anandinasu** [comment]
Hello @Jason3S,

Everything is working fine now as expected. Thank you for fixing this asap.
