### ISSUE TITLE
add to folder doesn't work when a workspace is open

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [streetsidesoftware/vscode-spell-checker#1341]
Since 2.x (i.e. broken as far back as 2.0.1, but was working in 1.10.2), I can no longer use the quick-fix to add a word to `.vscode/settings.json` within a folder when a workspace is open. I can add to user and workspace settings, and if I close the workspace and just open the folder, I can add to the folder settings _then_.

But if I try to add to folder settings when a workspace is open, I get a `Unable to add "word"` toast. No details on what the underlying error was appear in the logs, which is unfortunate, but [does match the code](https://github.com/streetsidesoftware/vscode-spell-checker/blob/7b53242c191572bfdf850ea28cfd4a617c235604/packages/client/src/settings/DictionaryHelper.ts#L83)

After spending some time figuring out how to attach a debugger to the extension host, I was able to throw a breakpoint on that line and note this error stack:
```
Error: Unable to write to Folder Settings because no resource is provided.
    at I.toConfigurationEditingError (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at I.validate (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at I.doWriteConfiguration (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at Object.factory (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at d.consume (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:77)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:77
    at new Promise (<anonymous>)
    at d.queue (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:77)
    at I.writeConfiguration (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at I.writeConfigurationValue (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935
    at Array.map (<anonymous>)
    at I.updateValue (vscode-file://vscode-app/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:1935)
    at processTicksAndRejections (internal/process/task_queues.js:93)
```

I wasn't able to get much farther than that working with minified code, and I've not yet figured out how to debug non-minified version of the extension

**Comment by Jason3S** [comment]
Thank you for the excellent report. I'll see if I can reproduce this.

**Comment by mgabeler-lee-6rs** [comment]
Confirmed 2.0.7 fixes this for me, thanks much for the fast fix!

**Comment by Jason3S** [comment]
Thank you for checking!

**Comment by ryan-feeley** [comment]
Unfortunately I'm still seeing this issue with v2.0.7 of the extension.

I think I have a fairly vanilla setup on Windows 10. No insiders builds. I have a single single-root workspace. I tried to add a word to the workspace manually using the settings editor, and that worked, but if I use either RMB - > Add Words to Folder Settings or 

Here is the content of my `*.code-workspace` file. It is just in the folder root (not a .vscode subfolder), which is where Code prompted me to save it. Perhaps the relative path and lack of an explicit folder name is a problem.
```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"cSpell.ignoreWords": [
			"pylance"
		]
	}
}
```

![image](https://user-images.githubusercontent.com/29698117/134828446-f3261e76-a611-4496-93cf-d2b3f53b34ad.png)

**Comment by ryan-feeley** [comment]
Update on my comment. The issue appears to be related to the new "Jupyter Notebook" editor. The file in question was a `*.ipynb` (Jupyter Notebook) file. If I right-click this file in the File Explorer, do "Open With" and choose the "Text Editor" to open the file, then "Add Words to Folder Settings" and "Add Words to Workspace Settings" **both work properly**.

It appears likely related to something here, which the (kick ass BTW) cSpell extension may not quite be inter-operating with yet.

[Native Notebook Support in VS Code](https://github.com/microsoft/vscode-jupyter/wiki/Native-Notebook-Support-in-VS-Code#enabling-the-new-experience)
[Notebook API](https://code.visualstudio.com/api/extension-guides/notebook)

Two other observations:

1. When I have a `*.ipynb` file open in the Jupyter Notebook editor, I don't get the "Add Words to Workspace Settings" option, even though I do have a workspace open in VS Code.
2. (This may be by design). If I work within the text editor, once I've successfully done "Add Words to Folder Settings", which creates a `.vscode/settings.json` file, the existence of that file **shadows** the "cSpell.words" in my `*.code-workspace` file. Words are added to that field as requested, but **cSpell ignores the whitelist in the `*.code-workspace` file**. It appears to fallback to a the unions of the whitelists in  `..\vscode\settings.json` and `.\cSpell.json`, but skips the works in the `*.code-workspace` file.

**Comment by ryan-feeley** [comment]
Thanks for creating the new issue https://github.com/streetsidesoftware/vscode-spell-checker/issues/1353. I which I knew enough to contribute to the solution.

Just one FYI on my observation `#2`

>     2. (This may be by design). If I work within the text editor, once I've successfully done "Add Words to Folder Settings", which creates a `.vscode/settings.json` file, the existence of that file **shadows** the "cSpell.words" in my `*.code-workspace` file. Words are added to that field as requested, but **cSpell ignores the whitelist in the `*.code-workspace` file**. It appears to fallback to a the unions of the whitelists in  `..\vscode\settings.json` and `.\cSpell.json`, but skips the works in the `*.code-workspace` file.

This appears to be an artifact of the VS Code design, which you're probably already aware of.

> Workspace Folder settings - Apply to a specific folder of a multi-root workspace. **Override User and Workspace settings**.

So once a user does "add words to folder settings", they generate a Workspace Folder settings entry (in `<folder>/.vscode/settings.json`) which by design would shadow any existing word list in the `*.workspace-code` file.

It does appear that the extension is able to merge User settings and Workspace-Folder settings, so perhaps there would be some way in the future to merge all three sources (plus those of any CSpell config files).

VS Code Documentation References:

* [Settings precedence](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence)
* [Multi-root Workspace Settings](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings)
