### ISSUE TITLE
Support Chinese

### ISSUE THREAD

**Issue by XXXXXLXL** [streetsidesoftware/vscode-spell-checker#1479]

**Comment by Pablion** [comment]
What do you mean by this? A translation of the setting interface?

**Comment by Jason3S** [comment]
@blank1u,

The spell checker is setup to ignore Chinese characters because they are whole words in themselves.

For the extension to support Chinese, the spell checker library needs to be able to support it.

Please open an issue here: [streetsidesoftware/cspell: A Spell Checker for Code!](https://github.com/streetsidesoftware/cspell)
