### ISSUE TITLE
Plugin not showing after installing

### ISSUE THREAD

**Issue by AlexFreik** [streetsidesoftware/vscode-spell-checker#2013]
I've installed the plugin (macOS Monterey 12.1, VScode 1.66.2). But it seems that nothing has changed. Spell mistakes are still not highlighted, and I don't even have a `cSpell` icon in the toolbar. 

I'm working with a TypeScript `.ts` file.
<img width="1436" alt="Screenshot 2022-06-11 at 11 13 41" src="https://user-images.githubusercontent.com/61039123/173181688-b0e5f6a7-ae87-443c-96a2-a6ce883ca6e4.png">

I tried to reload the window several times, disabled/enabled the plugin, reinstalled the plugin, plus restarted VS code, but nothing changes.

**Comment by Jason3S** [comment]
@AlexFreik,

Is it possible to update VS Code? The current version is 1.68.0.

If that doesn't work, delete:

```
~/.vscode/extensions/streetsidesoftware.code-spell-checker*
```

restart VS Code and install the extension again.

**Comment by AlexFreik** [comment]
> restart VS Code and install the extension again.

Oh, now it works, haha) Thanks a lot!

**Comment by Lemmingh** [comment]
@Jason3S

There is a mismatch since PR #1995 ([`v2.2.2`](<https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v2.2.2>)), causing this issue.

The `vscode-languageclient` version `8.0.1` requires VS Code version `^1.67.0`:

<https://github.com/microsoft/vscode-languageserver-node/blob/8b3c375adc4fa69f63726ef58d911c8e27b261c5/client/package.json#L8>

But `code-spell-checker` still declares `^1.59.1`:

<https://github.com/streetsidesoftware/vscode-spell-checker/blob/fbf0a00d3b82a9b339bd3ffc9d744d2a34cb39f8/package.json#L21>

**Comment by Jason3S** [comment]
@Lemmingh,

Thank you. I think I patched it in the wrong place.

**Comment by Jason3S** [comment]
For those using VS Code older than 1.67.0, please use 2.2.1 version of this extension.
