### ISSUE TITLE
Why doesn't the Spell Checker Extension read `cSpell.words`?

### ISSUE THREAD

**Issue by aleshaio** [streetsidesoftware/vscode-spell-checker#2209]
![image](https://user-images.githubusercontent.com/115655/188790794-000423cc-0644-4b5d-925f-5f3d98dbcb66.png)

Did nothing with cSpell, it just starts working when it wants, and I don't know WTF is going on now. When it works → you add some words to custom dictionary, they just dissapears. User, Folder, Workspace. Tried all. So I need make some file, probably, just for cSpell. 

The most random spell checker ever.
I don't know what issue is that. But your spellchecker don't see any words nor in folder settings, nor in workspace.

Typescript / VSCode latest. Here the screenshot of my workspace where I'm now. And cSpell words that cSpell can't see. /facepalm.

Gone for another spellchecker. 
Waste of time and nerves.

**Spellchecker that steal your time instead of give you extra.**

**Comment by Jason3S** [comment]
@aleshaio,

Thank you for your feedback. It is clear your are frustrated. I'll try to answer it because maybe other people are having the same problem.

The way VS Code assembles settings is non-obvious. See: [Settings Precedence: Visual Studio Code User and Workspace Settings](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence). The spell checker receives the final result after VS Code has merged the settings using its precedence rules.

Things that can go wrong:
1. `cSpell.words` at the folder level block `cSpell.words` at the workspace level or user level. This is most likely what is happening in your case. 
2. There is a syntax error in a `.vscode/settings.json` or `*.code-workspace` file. If that happens, VS Code will not correctly assemble the settings.

If you have a monorepo style project, I suggest adding a `.cspell.json` file to the root:

```json
{ "words": [] }
``` 

The spell checker will automatically find the file and use it.

Kind regards,
Jason

**Comment by aleshaio** [comment]
@Jason3S 

Thanks, Jason. Already removed VS Code and bought PHP Storm. 
Problem solved.
