### ISSUE TITLE
Manage regex comparison time

### ISSUE THREAD

**Issue by ghost** [streetsidesoftware/vscode-spell-checker#227]
_Feature request / improvement:_

If a very time expensive regular expression is written in `cSpell.ignoreRegExpList` this can lead to the spell checker becoming unresponsive / not updating, and maxing out the processor.

Can some way of prioritising user interaction over regular expression checks be made (i.e. so the suggestion light bulb still works while a regular expression checks are being made)? Or highlight that a regular expression is taking up a lot of time to run against the text being spell checked.

Example regular expression to add to `cSpell.ignoreRegExpList` that cause the spell checker to go slow on my machine for about 5-10 minutes on a reasonable sized project:

`"``(\\w*\\d*\\s*_*-*;*)+``"`
(Double "`\`" for .JSON formatting)

(I do know the above regular expression can be written in a better wat, to stop this being an issue, its just an example to cause the described behaviour.)

**Comment by Jason3S** [comment]
I can see how this can be an issue. I have had it happen to me. Sadly, I do not have an easy way to detect and kill long running regex.

But there is a change coming to regex support. At the basis, it will only check a single line at a time as opposed to the entire file. This will prevent these extreme check times due to shorter strings.

This change will break existing multi-line regex expressions. But an alternative will be provide through a `{"begin": "regex for the start", "end": "regex for the end"}`

**Comment by Asho555** [comment]
Cool! Single line checks sounds like it would solve it.

Or perhaps, or in the mean-time, changing the 'default' comment before `cSpell.ignoreRegExpList` to warn anyone writing new regex patterns in that it can become an issue. I know it took me longer than I want to admit to find that being the issue.

But otherwise great extension!

**Comment by dossy** [comment]
It appears that single line checks have been implemented, which means I can't write an ignore regexp like `<style[^>]*>.*?</style>` to ignore all inline CSS sections of files.

Any chance support for modifiers like `(?s)` to enable full-file matching for regexp's that require it could be implemented?

**Comment by Jason3S** [comment]
> It appears that single line checks have been implemented, which means I can't write an ignore regexp like `<style[^>]*>.*?</style>` to ignore all inline CSS sections of files.
> 
> Any chance support for modifiers like `(?s)` to enable full-file matching for regexp's that require it could be implemented?

`.*?` will not cross a line boundary. Something like this will:
```
<style[^>]*>[^\1]*?</style>
```
You can use https://www.regex101.com to try out your expressions. Use the JavaScript flavor.

**Comment by Jason3S** [comment]
See https://github.com/streetsidesoftware/vscode-spell-checker/issues/650#issuecomment-756635327 on how to show the RegExp Explorer.
