### ISSUE TITLE
Bug: "Enable spell checking for document language" enables ALL languages.

### ISSUE THREAD

**Issue by gandalfsaxe** [streetsidesoftware/vscode-spell-checker#248]
1. Start with no `.vscode/settings.json` file:
2. Run "Enable spell checking for document language"
Result:
```json
{
    "cSpell.enabledLanguageIds": [
        "asciidoc",
        "c",
        "cpp",
        "csharp",
        "css",
        "go",
        "handlebars",
        "html",
        "jade",
        "javascript",
        "javascriptreact",
        "json",
        "latex",
        "less",
        "markdown",
        "php",
        "plaintext",
        "pub",
        "python",
        "restructuredtext",
        "rust",
        "scss",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ]
}
```
(why are all other formats added?)
3. Run "Disable spell checking for document language"
```json
{
    "cSpell.enabledLanguageIds": [
        "asciidoc",
        "c",
        "cpp",
        "csharp",
        "css",
        "go",
        "handlebars",
        "html",
        "jade",
        "javascript",
        "javascriptreact",
        "json",
        "latex",
        "less",
        "php",
        "plaintext",
        "pub",
        "python",
        "restructuredtext",
        "rust",
        "scss",
        "text",
        "typescript",
        "typescriptreact",
        "yml"
    ]
}
```
i.e. markdown is removed ,but everything else remains.

Shouldn't it just add/remove markdown with those two commands?

**Comment by Jason3S** [comment]
This has to do with how VS Code settings work.

Having `"cSpell.enabledLanguageIds"` in a folder level `.vscode/settings.json` file will override all global and default settings. This is due to how VS Code handles settings.

To prevent unexpected behavior, when you enable / disable a language, it ensure that the spell checking setting is preserved for all other languages. To do that, it needs to copy all the global / default settings locally.
