### ISSUE TITLE
Relative path to custom dictionary not working as expected.

### ISSUE THREAD

**Issue by gandalfsaxe** [streetsidesoftware/vscode-spell-checker#262]
cSpell words fine for me when I have my words in either `settings.json` or `cSpell.json`, but it doesn't work if I have in `cSpell.json`:

```json
  // Version of the setting file.  Always 0.1
  "version": "0.1",

  // language - current active spelling language
  "language": "en",

  "dictionaryDefinitions": [{ "name": "test", "path": "./test.txt" }],
  "dictionaries": ["test"]
```

And a file `test.txt` with words, one per line, also in the `.vscode` folder. Isn't this supposed to work?

**Comment by GandalfSaxe** [comment]
The paths doesn't seem relative to `cSpell.json` as the documentation said, but the workspace itself? Also I can't get it to work from `cSpell.json`.

I finally got it working with two modifications:

1. Made paths relative to workspace instead of path of `cSpell.json`
2. Added to `settings.json` instead of `cSpell.json`

I.e. added the following to `settings.json` instead, also adding `cSpell.` in front of commands:

```
  "cSpell.dictionaryDefinitions": [{ "name": "test", "path": "./test.txt" }],
  "cSpell.dictionaries": ["test"]
```
