### ISSUE TITLE
"C Spell: Spell Check Only Workspace Files" spell checks unsaved content

### ISSUE THREAD

**Issue by paleite** [streetsidesoftware/vscode-spell-checker#2657]
First off, thanks for a great plugin! I use it daily, and recommend it to ALL of my co-workers.

The content is spell-checked before it's a file in the workspace.

I don't know if it's by design (i.e. most users will want to spell-check the files before they're saved), but I found it confusing, because I usually have unsaved content in my editor where I use other languages, and I would like to disable spell-checking on them.

Maybe there's another way to achieve what I'm after?

Any help appreciated 🙂

**Comment by Jason3S** [comment]
@paleite,

Checking files before they are saved is by design.

Two options:

1. Turn off the "untitled" schema by removing it from `cSpell.allowedSchemas`.
   <img width="941" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/6854e030-a509-45eb-8803-e22d128cd8e2">

2. Install one of the language extensions. Adding a `cspell` directive in a comment can be used to enable it. Example, `<!--- cspell:locale en,sv --->` can be used to enable English and Swedish in the document.

**Comment by paleite** [comment]
Awesome! Thanks, @Jason3S 🙂 i'll close the ticket. Appreciate the help.
