### ISSUE TITLE
no commands found, despite multiple uninstall/reinstall cycles

### ISSUE THREAD

**Issue by shadowimmage** [streetsidesoftware/vscode-spell-checker#278]
no matter what I do, none of the spell checking functionality is working from this extension. I have checked the settings, and they look right. 

There are no errors anywhere in the consoles/output, and every time I try to run a cSpell command, an error comes up:
- command 'cSpell.displayCSpellInfo' not found
- command 'cSpell.toggleEnableSpellChecker' not found
- etc... 

Not sure how to debug this or where even to look for where these errors are coming up from; not sure how to proceed. Would love to be able to resolve this.

**Comment by shadowimmage** [comment]
found this in the developer tools console: 
`Activating extension 'streetsidesoftware.code-spell-checker' failed: Cannot find module 'C:\Users\Chase Sawyer\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\out\src\extension'.`

**Comment by shadowimmage** [comment]
there is no directory `...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\out\src\extension`
but there is `...\.vscode\extensions\streetsidesoftware.code-spell-checker-1.6.10\out\src\client`

**Comment by Jason3S** [comment]
Sorry for taking so long to get back to you. Did you manage to get it to work?

Generally the install issues are caused by VS Code. You have to:

- Uninstall the extension
- Quit VS Code
- Make sure all VS Code processes are gone.
- Start VS Code
- Install the Extension

I'm not sure why this happens, but it seems to happen after a VS Code update.

**Comment by Jason3S** [comment]
Thank you. It is very strange that the full install didn't work.
