### ISSUE TITLE
It is warning about parts of a string as an unknown word

### ISSUE THREAD

**Issue by RichardNorton** [streetsidesoftware/vscode-spell-checker#2924]
For the string `toLowerCase` it warns `"ower": Unknown word.cSpell`.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/92771594/f7738267-8be0-475c-af7b-d5eb26fb48c1)

This has started recently but cannot remember when exactly.

Visual Studio Code: v1.84.1
Code Spell Checker: v3.0.1

**Comment by Jason3S** [comment]
@RichardNorton,

There is something else going on. It is most likely a regular expression in the configuration.

Do you have any values in `.vscode/settings.json` `cSpell.ignoreRegExpList` or `ignoreRegExpList` in a cspell config file?

You can visualize the regular expressions by using one of the Extension's experimental features.

There is an experimental setting in the extension that measures regexp performance.
From VS Code settings, enable `cspell Experimental Enable Regex View`
![image](https://user-images.githubusercontent.com/3740137/103994648-92d0c880-5197-11eb-88f5-0fd19f0c2d48.png)

You might need to restart vscode due to a settings bug in vscode.

Then click on the "check" in the side bar:
![image](https://user-images.githubusercontent.com/3740137/103994803-cf042900-5197-11eb-8868-de530ed266ea.png)

You will see something that looks like this:
![image](https://user-images.githubusercontent.com/3740137/103994878-ed6a2480-5197-11eb-9b43-75f4dc74f65b.png)

By selecting an expression, it will highlight it in the current document.

<img width="722" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/95687ad2-dcc4-4c20-861f-acdf8334bba0">

**Comment by RichardNorton** [comment]
I have one entry in `ignoreRegExpList` which is a regex I've added. Using the `cSpell.experimental.enableRegexpView` setting I can see that in operation and it is not highlighting the unknown word or its containing string. 

Also the unknown word is only showing in one instance of a particular string when the string is in the file many times.

To make it even more confusing if I remove my entry from `ignoreRegExpList` the unknown word issue goes away.

**Comment by Jason3S** [comment]
@RichardNorton,

Please share the contents of `ignoreRegExpList`.

**Comment by RichardNorton** [comment]
"cSpell.patterns": [
      {
        "name": "firebaseId",
        "pattern": "-(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{19}"
      }
    ],
    "cSpell.ignoreRegExpList": [
      "firebaseId"
    ],

**Comment by Jason3S** [comment]
It does match:

<img width="624" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/0cd8e76c-97f2-4847-89ac-aa6a7c79136d">

[regex101.com](https://regex101.com/r/hcFP2C/1)

Please note: if regexp flags are not given, `gim` is used: `/-(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{19}/gim`.

I'm not sure if `/-(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{19}/gim` is what you want to use to match firebase IDs.

 
<img width="778" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/a236a4d1-f007-47b5-bf8f-e93cd2036926">

**Comment by RichardNorton** [comment]
The regular expression does match, but that is ignored in the spelling mistakes as it should be. The problem I have is it finds part of an existing  valid word and claims it's incorrect.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/92771594/66814fc6-6af8-4108-80cd-7514b88d5fb4)

Is this a bug or am I using the `cSpell.ignoreRegExpList` setting incorrectly?

**Comment by Jason3S** [comment]
@RichardNorton,

`cSpell.ignoreRegExpList` is applied to the document before spell checking is done. Only sections of the document that are not ignored are checked. In your case it is effectively cutting `toLowerCase` into `toL` (ignored) and `owerCase` (checked).

A future enhancement would be to add a new setting: `cSpell.allowWordsMatchgRegExpList`, this setting would be applied to words that are considered misspelled.

**Comment by RichardNorton** [comment]
Thank you for your help. Now that I know the reason I've tweaked my regex to only check strings within quotes with no spaces so this negates the partial word misspelling issue.
