### ISSUE TITLE
Spelling error does not seem to be detected when there is a number in the middle of word.

### ISSUE THREAD

**Issue by SayYoungMan** [streetsidesoftware/vscode-spell-checker#2942]
# Introduction

Hello! I've been using your extension on VS code and I've loved it so far.
I was working on a markdown file and I made a typo of `be4cause` instead of `because`.
However, it didn't show an error of unknown word which was expected.

Was this done on purpose?

# Reproduction

With the extension enabled type a word with number in the middle.
<img width="309" alt="Screenshot 2023-11-21 at 21 12 46" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3970356/aea1ca5c-3dd7-4c71-a8a2-c4f01e281025">

Expected behaviour: To underline saying it's an unknown word.
Actual behaviour: Does not show any warning.

**Comment by Jason3S** [comment]
@SayYoungMan,

Thank you. It is by design that the spell checker will attempt to split words on non-letter boundaries. It is a common coding practice to use number is variable names, like: `meters2feet`. A future enhancement might be to all selecting a different word splitter based upon the file type.
