### ISSUE TITLE
disable "refresh" frame in status bar

### ISSUE THREAD

**Issue by Evileoo** [streetsidesoftware/vscode-spell-checker#3190]
The spell issues in status bar are as annoying as useful

[video-4-15-a-1149_c0hv8e8s.webm](https://github.com/streetsidesoftware/vscode-spell-checker/assets/54958225/4b3b90cc-e28a-48da-9ac7-43b7a33ccc4a)

Is it possible to hide or disable the "refresh" frame ?

Thanks

**Comment by Jason3S** [comment]
@Evileoo,

I can see how that would be very annoying. It is can be caused by a couple of things:
1. Another extension changing the active editor in the background.
2. Another extension/process causing the VS Code settings to get updated.

If you turn off other extensions, does it still happen?
See: https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect

**Comment by Evileoo** [comment]
Okay I still got it yesterday, and somehow, I don't get it anymore...

I'll let you know if it happens again

I leave the the issue open just in case (I'll close it if nothing happens in following weeks)

**Comment by Jason3S** [comment]
@Evileoo,

It can also be caused by settings synchronization if it gets caught in a loop: [Settings Sync in Visual Studio Code](https://code.visualstudio.com/docs/editor/settings-sync).

When the Spell Checker's settings change, it effectively causes all document to be spell checked again. The flash you see is caused by the spell checker waiting for the check to complete. It first goes into an unknown state, followed by the update.
