### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by puebla93** [streetsidesoftware/vscode-spell-checker#339]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.7.9`
- OS Version: `Linux x64 4.15.0-38-generic`
- VSCode version: `1.33.1`

[streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt](https://github.com/Jason-Rev/vscode-spell-checker/files/3159441/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
Thank for including the attached file.
I need more information:
* What kind (text, cpp, python, etc) of files are you editing?
* Are there lots of files in your project?
* Do you have a workspace plus folders?
* How large are the files?

**Comment by Jason3S** [comment]
Thank you for attaching the file. That makes a big difference.
The strange issue is that it seems to be stuck in the VS Code extension loader. But the extension is NOT loaded. It is acting like VS Code is not able to find the extension.

What happens if you restart VS Code and re-install the extension?

**Comment by Jason3S** [comment]
I am hoping this is fixed with 1.7.10. I have bundled the extension as described by 

[Explain: extension causes high cpu load · code-loading](https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load#code-loading)
