### ISSUE TITLE
Generates settings.json in every workspace 

### ISSUE THREAD

**Issue by a2937** [streetsidesoftware/vscode-spell-checker#3420]
I don't mind having a settings.json for what languages it is enabled, but I would like to have a say in it. Creating one should be handled by a command. If one isn't present, it should just read the global settings file.

**Comment by Jason3S** [comment]
@a2937,

Thank you for the report. It should only write to settings if you add words. In general is also gives the option to add the word to `User` or `Workspace`. Are you experiencing something different?

**Comment by a2937** [comment]
I am actually. I am getting a list of enabled languages written every time a folder gets opened. 

Steps to repeat. 

Prerequisite: Install the Code Spell Checker language pack. 

Step 1) Open a folder in the File explorer that doesn't have a settings.json. 
Step 2) Wait a few minutes. 
Step 3) Notice new settings.json with enabled language ids list. 


[settings.json](https://github.com/user-attachments/files/16101174/settings.json)

**Comment by Jason3S** [comment]
@a2937,

That is strange. I can see how it would be annoying.

On its own, the spell checker will not change the settings. That only happens if a command is run.

I guessing you are running version `v3.0.1` of the extension.

Please make sure that there isn't a keyboard shortcut associated with any of the following commands:
- `cSpell.enableLanguage`
- `cSpell.disableLanguage`
- `cSpell.enableCurrentLanguage`
- `cSpell.disableCurrentLanguage`

<img width="1383" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/e30c50fa-ce1a-443f-81fe-75c0e97533bd">

These commands enable/disable file types (Language Ids). They are not for enabling natural languages.

The `cSpell.language` setting is used for enabling English, Spanish, etc.

If you are using those commands to enable / disable the spell checker, consider upgrading to v4. It has a very easy way to hide/show issues.

**Comment by Jason3S** [comment]
It might also be a `sync` issue caused by VS Code, since it is take a few minutes to happen.
