### ISSUE TITLE
set cSpell.showStatus to false by default

### ISSUE THREAD

**Issue by cancerberoSgx** [streetsidesoftware/vscode-spell-checker#361]
The status icon is not really helpful and is really annoying since often users click it unintentionally and since its split the editor, steal focus and show the big green banner basically makes one loose focus at all. Also probably you need to use the mouse to close it. 

Besides not the status button nor the the editor that opens have any relevant information for the user. I this could be an issue for users to use another alternative than this project, is my only complain the rest is perfect. 

The only perhaps, relevant information (although not useful for me) is if the current document has spell checking enabled, if you really want to show that info by default, then it should be shown at the right bottom corner (where other secondary information is shown) but where it currently is (left bottom) is surrounded by very useful things and since buttons are tiny it's activated without intention often and annoyingly as explained before.  

Thanks! keep it up!

**Comment by Jason3S** [comment]
Thank you for the feedback. VS Code has evolved a bit since this extension was first developed. It has always been possible to turn off having it show in status bar. The idea is to indicate that the file is being spell checked. But you make a good point about moving it to the right and making it a bit more compact.

It is easy to turn off with the latest version of VS Code. Just right click the status bar:
![image](https://user-images.githubusercontent.com/3740137/60975807-d6414100-a32c-11e9-9cbc-8a74544e3faf.png)

You will get something like this.

**Comment by Jason3S** [comment]
The Status Bar item has been moved to the right-hand side.
