### ISSUE TITLE
VSCode spell-checker extension not updating beyond v3.0.1

### ISSUE THREAD

**Issue by metablaster** [streetsidesoftware/vscode-spell-checker#3775]
My Code Spell Checker is not updating, it stays at v3.0.1 and that's maximum available version to install since long time ago and I have this problem only with Code Spell Checker so I think it's better to create the issue here than on VSCode repo:

![cspell](https://github.com/user-attachments/assets/723e7d2a-d899-4842-a9f5-e133c91ac335)

![cspell2](https://github.com/user-attachments/assets/4a27272c-bfdc-4d1a-b950-dd200598ab07)

I also verified the extension is not installed for all profiles as per [this issue](https://github.com/microsoft/vscode/issues/214778)

![cspell3](https://github.com/user-attachments/assets/03812389-8443-4c13-8ae8-a6cffa1f9cb8)

Btw. I manually check for extension updates, all other extensions update fine.

**Comment by metablaster** [comment]
I figured out I needed to `Switch to Pre-Release Version` to get the latest published version installed.

My I suggest that you don't label your tags on GitHub as "Latest Release" unless it's an actual release?

A standard way to publish Pre-release tags on GitHub is to mark them as "Pre-release" by checking the checkbox while tag is published.

All this time I was under impression these releases on GitHub are releases because they were marked so.

**Comment by Jason3S** [comment]
@metablaster,

I had been holding off Releasing 4.x until it was polished and the documentation up to date. Mostly clean up items that have been holding it back. The core functionality is solid.

I think the real issue with `preview` is around the VS Code interface. It is not obvious that there are preview versions since they do not show up in the dropdown list.

In any case, I think the new functionality is more important to release than waiting for all the clean-up items to complete.

**Comment by metablaster** [comment]
@Jason3S 

> In any case, I think the new functionality is more important to release than waiting for all the clean-up items to complete.

Thank you for attention, and I agree with this, I think every tag on GitHub that's marked as `Release` instead of `Pre-Release` should be accessible in VSCode without having to switch to pre-release manually.

I'll close this since it's solved for me.
