### ISSUE TITLE
Code spell checker CPU usage

### ISSUE THREAD

**Issue by justisGipson** [streetsidesoftware/vscode-spell-checker#393]
CPU usage viewed via top and process helper claimed this extension was using 156% of CPU while fixing an app's JSON file. I can re-enable and send screen shots if needed. I had disabled it before starting this issue.

**Comment by memeplex** [comment]
I'm seeing a lot of high CPU usage due to this spell checker also, I've to disable it because it was draining my battery.

**Comment by Jason3S** [comment]
@memeplex I would like to find out the issue.
In regular usage, this does not happen.

Common causes:
1. Incomplete install / update - this occasionally happens when VS Code installs / updates the extension. For some reason, it does not manage to download the entire extension and VS Code goes into a infinite loop trying to load the extension. The fix in this case is to uninstall the extension and to erase the cached copy from VS Code before reinstalling it.
1. A runaway regex in the include / ignore section see [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)
1. A very large file
1. Something else - this is where I need your help.

* Can you include a copy of your `cspell.json` file or the `cSpell.*` sections of the VS Code `settings.json` file.
* Please let me know the programming language and approximate size of the file.
* What OS are you using?
* Please include a copy of the VS Code About dialog.
* If you happen to have a public repository that exhibits this behavior, please send me a link.

**Comment by Jason3S** [comment]
@justisGipson Is this still a problem? If so, I would like to find out the cause.

**Comment by justisGipson** [comment]
It is. I tried reinstalling the extension yesterday only to see the same high cpu usage.

**Comment by Jason3S** [comment]
Please see #431.
Could you also share what type of files you are editing and any regular expressions you have in your settings or `cspell.json` files?

**Comment by Jason3S** [comment]
@justisGipson please try again with v1.8.0.
If it is still happening, please provide the list of regular expressions you are using.

**Comment by justisGipson** [comment]
@Jason3S I haven't tried re-installing the extension. I've also since cleaned up my code spell json stuff since I've stopped using it on my work machine. I still have all the info on my personal machine at home. I will try to get you the info in the next couple of days to get this wrapped up.

**Comment by Jason3S** [comment]
Thank you.
