### ISSUE TITLE
Github releases do not indicate prerelease status

### ISSUE THREAD

**Issue by twelvelabs** [streetsidesoftware/vscode-spell-checker#3974]
I was just comparing the extension version in VS Code with the latest version in [the GH releases page](https://github.com/streetsidesoftware/vscode-spell-checker/releases), and was a bit confused as why they were out of sync (despite having the extension configured to auto-update). It appears that you are submitting them to the VS Code marketplace as prereleases, but to GH as regular ones. Would you mind configuring your automation to submit the GH releases as prereleases, too? Might help prevent future confusion.

It looks like you recently setup a tool for managing the prerelease setting here: bf69a1a3addcc992282248d8ef602444ece3b876. I did a (very) brief check of `release-please`, and it _looks_ like they have some kind of prerelease option... maybe `scripts/set-prerelease-mode.js` can update that as well 🤷 .

**Comment by Jason3S** [comment]
@twelvelabs,

You are the second person in the past month that brought this up. After looking at the [Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) entry, I can see that it is not clear which version is `pre-release` and which one is not. I remember it being easy to tell.

I'll take a look at release-please config to see if it possible. The issue is that the VS Code Marketplace doesn't support release version tags like `-beta01`, which is how most packages indicate that it is prerelease. VS Code marketplace expects you to set a command-line flag when the extension is packaged: [Publishing Extensions | Visual Studio Code Extension API](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions).

**Comment by Jason3S** [comment]
@twelvelabs,

It sets it as `pre-release` after the release is made, but it should be clear for anyone reading it.
