### ISSUE TITLE
Adding to folder dictionary silently 'fails'

### ISSUE THREAD

**Issue by JoostFromMicrosoft** [streetsidesoftware/vscode-spell-checker#463]
We maintain a team-wide cSpell config file in our repository. This configuration file is only picked up if the user opens the 'correct' workspace (e.g. opens the folder containing the cSpell.json, rather than a parent or child folder). If the user opens VSCode in some other way and then uses the context menu action 'add to folder dictionary', the action is silently redirected to the .vscode/settings.json file. This causes the team's cSpell config to drift: instead of a centralized cSpell config file, settings are distributed among .gitignored .vscode config files. So for our team's workflow this is essentially a silent failure.

Possible resolutions:

 - Emit a warning when the VSCode config file rather than the cSpell config file is modified.
 - Split the 'add to folder dictionary' action into separate actions for cSpell.json and settings.json. For either action, emit an error if it fails.

The first option is the simplest to implement, but might be noisy for some workflows.

**Comment by JoostFromMicrosoft** [comment]
Possibly related: #315.

**Comment by Jason3S** [comment]
Thank you Joost.
I will take a look at your PR.

There are two longer term items I want to implement / clarify:
1. A way to specify the location to add words. Having them added to the cspell.json file is not the right way.
2. Clean logic on where to find `cspell.json` files in a project. Like in your case if someone opens a sub folder instead of the root.

**Comment by Jason3S** [comment]
Hello Joost,

There are three basic flows where the spell checker is used:
1. Part of an organization that uses `cspell.json` files.
1. Part of an organization that share VS Code configuration (no cspell.json files)
1. Part of an organization that does not use cSpell or VS Code, but the individual developer loves VS Code so much that they have added `.vscode` to their global `.gitignore`.

PR #464 addresses the first use case, but not the other two. For them, it would be annoying to get a warning whenever they add a new word.

If we go back to the goal: avoid adding words to the VS Codes settings when there is a shared dictionary for an organization / project.

I had not addressed #315 because it is not so simple. As in your case, someone opens VS Code in a subdirectory instead of at the workspace root. How to detect that situation?

I am open to ideas.

**Comment by Jason3S** [comment]
@JoostFromMicrosoft 

Would you try out: [v1.9.0-alpha.0](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v1.9.0-alpha.0)

**Comment by Jason3S** [comment]
The way it works in V2 has changed. If this is still an issue, please one a new issue describing the desired behavior.

Kind regards,
Jason
