### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kemalgencay** [streetsidesoftware/vscode-spell-checker#480]
[streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt](https://github.com/streetsidesoftware/vscode-spell-checker/files/4572999/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt)

- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.8.0`
- OS Version: `Linux x64 5.3.0-51-generic`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/kemal/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
Number 1 and 2 below are most likely.

Common causes:
1. Incomplete install / update - this occasionally happens when VS Code installs / updates the extension. For some reason, it does not manage to download the entire extension and VS Code goes into a infinite loop trying to load the extension. The fix in this case is to uninstall the extension and to erase the cached copy from VS Code before reinstalling it.
1. A runaway regex in the include / ignore section see [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)
1. A very large file
1. Something else - this is where I need your help.

* Can you include a copy of your `cspell.json` file or the `cSpell.*` sections of the VS Code `settings.json` file.
* Please let me know the programming language and approximate size of the file.
* What OS are you using?
* Please include a copy of the VS Code About dialog.
* If you happen to have a public repository that exhibits this behavior, please send me a link.

Please see
#431 #393 #388 #278

**Comment by Jason3S** [comment]
Closing for now.
