### ISSUE TITLE
Long Quick Fixes search

### ISSUE THREAD

**Issue by irvnriir** [streetsidesoftware/vscode-spell-checker#521]
With en-US + ru dictionaries, it take ~5s to show or update the bulb icon and the hover window says "searching" even longer .

Previously i used ban.spellright , and it didn't have noticeable delay in this (but is worse in all other) .

win10

**Comment by Jason3S** [comment]
I have updated the Russian dictionary. Please let me know if it has improved.

**Comment by irvnriir** [comment]
@Jason3S hasn't at all, i think that fixing this require to rework the comparison function/-s

**Comment by Jason3S** [comment]
This should be fixed. A time limit has been added. By default it is 400ms.

![image](https://user-images.githubusercontent.com/3740137/133894284-7dd15a82-1acb-4dc6-b6d5-3babcbc92761.png)

**Comment by irvnriir** [comment]
@Jason3S and how stopping the function halfway, can solve this issue ?

**Comment by Jason3S** [comment]
If there is a close match, it will find that one very fast. But the more changes it has to try to find a match, the longer it takes. It is possible to stop the search at any time.

**Comment by irvnriir** [comment]
@Jason3S would limitation by amount of changes be more logical then ?

**Comment by irvnriir** [comment]
The time limit has an advantage for small words, maybe an additional limit for minimum of changes to check ?

**Comment by Jason3S** [comment]
It has always been number of changes based, but that setting was not exposed.

The the recent addition was to limit the time in addition to the number of changes.

![image](https://user-images.githubusercontent.com/3740137/133927631-78897c63-79c5-4600-9f28-c8858cb2e6d1.png)

That number is not exact, meaning some types of changes are considered "cheaper" than others. Adding an accent or changing the case of a letter is very cheap.

The problem comes from long compound words.
