### ISSUE TITLE
Add All to dictionary - feature request

### ISSUE THREAD

**Issue by lukaszpolowczyk** [streetsidesoftware/vscode-spell-checker#563]
Add All to dictionary - feature request
One click add All custom words do cspell dictionary.

After that, the user can manually remove the actually misspelled words from vscode settings file.

**Comment by justingrant** [comment]
This would be, by far, the most useful change that this extension could make, because when working in a new repo, there are frequently hundreds of custom words. Adding them one at a time is incredibly time consuming. 

Note that there should be "add all" variations for all three destinations: user settings, workspace settings, and folder settings.

**Comment by Jason3S** [comment]
@justingrant,

Please try:
1. Opening a document with lots of issues.
2. Run the command: `Add All Spelling Issues to Dictionary`
   <img width="392" alt="image" src="https://user-images.githubusercontent.com/3740137/208352510-70d3d393-3e11-4e7f-a72f-12b08b9d5ba2.png">

**Comment by justingrant** [comment]
Great!  Thanks @Jason3S. One suggestion: it'd be ideal if these options were more discoverable, e.g. in the Quick Fix menu shown in VS Code. This is is what ESLint and Prettier do.

**Comment by Jason3S** [comment]
@justingrant,

I agree, they could be more discoverable. Documentation could also use some work.

**Comment by Jason3S** [comment]
I'm going to close this as done, since it is possible with commands.
