### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LuckyLeaolly** [streetsidesoftware/vscode-spell-checker#623]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.10.2`
- OS Version: `Darwin x64 20.1.0`
- VSCode version: `1.51.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/zz/s9np45ns2q9b0d9zvk9rsdd00000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
Hello @LuckyLeaolly,

It can be very frustrating when that happens.

A few questions:
1. What kinds of files are you editing?
1. Would you provide a link to a repository so we can reproduce the issue?
1. Have you added any regular expressions to `ignoreRegExpList`?

From: https://github.com/streetsidesoftware/vscode-spell-checker/issues/393#issuecomment-586713148

In regular usage, this does not happen.

Common causes:
1. A runaway regex in the include / ignore section see [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)
1. Incomplete install / update - this occasionally happens when VS Code installs / updates the extension. For some reason, it does not manage to download the entire extension and VS Code goes into a infinite loop trying to load the extension. The fix in this case is to uninstall the extension and to erase the cached copy from VS Code before reinstalling it.
1. A very large file - Add it to the `ignorePaths`.
1. Something else - this is where I need your help.

* Can you include a copy of your `cspell.json` file or the `cSpell.*` sections of the VS Code `settings.json` file.
* Please let me know the programming language and approximate size of the file.
* What OS are you using?
* Please include a copy of the VS Code About dialog.
* If you happen to have a public repository that exhibits this behavior, please send me a link.
