### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by akashkhairnar01** [streetsidesoftware/vscode-spell-checker#650]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.10.2`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.52.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/ly/_xt55f4167n_2n65709cq6tc0000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Voultapher** [comment]
I'm seeing the same problem on Linux x64 5.9. It pins one CPU core to 100%. Pretty distracting, so I'm turning the extension off for now.

**Comment by Jason3S** [comment]
Hello @akashkhairnar01 and @Voultapher,

It can be very frustrating when that happens.

A few questions:
1. What kinds of files are you editing?
1. Would you provide a link to a repository so we can reproduce the issue?
1. Have you added any regular expressions to `ignoreRegExpList`?

From: https://github.com/streetsidesoftware/vscode-spell-checker/issues/393#issuecomment-586713148

In regular usage, this does not happen.

Common causes:
1. A runaway regex in the include / ignore section see [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)
1. Incomplete install / update - this occasionally happens when VS Code installs / updates the extension. For some reason, it does not manage to download the entire extension and VS Code goes into a infinite loop trying to load the extension. The fix in this case is to uninstall the extension and to erase the cached copy from VS Code before reinstalling it.
1. A very large file - Add it to the `ignorePaths`.
1. Something else - this is where I need your help.

* Can you include a copy of your `cspell.json` file or the `cSpell.*` sections of the VS Code `settings.json` file.
* Please let me know the programming language and approximate size of the file.
* What OS are you using?
* Please include a copy of the VS Code About dialog.
* If you happen to have a public repository that exhibits this behavior, please send me a link.

**Comment by Voultapher** [comment]
Thanks for help @Jason3S 

Indeed, I have regex configured:

```
"cSpell.enabled": true,
    "cSpell.includeRegExpList": [
        "\\/\\/[^\\n\\r]*[\\n\\r]*",
        "\\*([^\\*]*\\*+[^\\*\\/])*([^\\*]*\\*+|[^\\*])*\\*"
    ],
    "cSpell.languageSettings": 
    [
        {"languageId": "plaintext", "includeRegExpList": [".*"] }
    ],
```

The idea is to only spell check inside comments.

I know of projects like https://github.com/rust-lang/regex that use a finite automaton

> This implementation uses finite automata and guarantees linear time matching on all inputs.

What regex implementation is used here? I'm open to help contributing such integration if you are intrested.

**Comment by Voultapher** [comment]
Regarding 2. how would I check that?

**Comment by Jason3S** [comment]
@Voultapher,

I'll take a look at your regexp. The second one looks very expensive. The spell checker is pure JavaScript for portability, so it uses the built-in regexp engine, which is not guaranteed to finish in linear time. Catastrophic backtracking is a problem. 

Note, there is already a predefined pattern for c-style comments:

to use:
```
    "cSpell.includeRegExpList": [
        "CStyleComment"
    ],

```

**Comment by Jason3S** [comment]
I'm not sure if the second expression does what you expect.  See: https://regex101.com/r/XsYwaR/1

There is an experimental setting in the extension that measures regexp performance.
From VS Code settings, enable `cspell Experimental Enable Regex View`
![image](https://user-images.githubusercontent.com/3740137/103994648-92d0c880-5197-11eb-88f5-0fd19f0c2d48.png)

Then click on the "check" in the side bar:
![image](https://user-images.githubusercontent.com/3740137/103994803-cf042900-5197-11eb-8868-de530ed266ea.png)

You will see something that looks like this:
![image](https://user-images.githubusercontent.com/3740137/103994878-ed6a2480-5197-11eb-9b43-75f4dc74f65b.png)

**Comment by Voultapher** [comment]
I never got it to even load the experimental view with the custom 'dumb' pattern, just one CPU core pinned, no response, even after closing vscode the process was still going. Using 'CStyleComment' fixes that, thank you. This solves the problem for me. Maybe as a suggestion, you could make it easier for people to know those built in patterns exist :)

**Comment by Jason3S** [comment]
I'm glad the built in expression worked.
