### ISSUE TITLE
en-GB does not work correctly, marks American spelling as correct

### ISSUE THREAD

**Issue by Bruncky** [streetsidesoftware/vscode-spell-checker#700]
If I turn off `en` (US) and turn on **only** `en-GB`, it still marks American spelling as correct. For example, both `organization` and `organisation` show as correct, but I would expect `organization` to be incorrect in this case.

Maybe there's a way to completely remove the US dictionary rather than just disabling it?

**Comment by Jason3S** [comment]
The spell checker uses the `en_GB-large` English dictionary from http://wordlist.aspell.net/hunspell-readme/

Since that dictionary is based upon the Oxford English dictionary, it includes words like `organization`. See [Oxford spelling - Wikipedia](https://en.wikipedia.org/wiki/Oxford_spelling)

For example, `color` is not part of the dictionary, but `colour` is.

**Comment by Bruncky** [comment]
I see, thanks for clarifying!
