### ISSUE TITLE
Too many Sync Reports

### ISSUE THREAD

**Issue by DeskYT** [streetsidesoftware/vscode-spell-checker#716]
Issue Type: <b>Bug</b>

1. Enable settings sync
2. write lorem100
3. add each word to user dictionary.

Extension version: 1.10.2
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Jason3S** [comment]
@DeskYT,

Thank you for bringing this up. I'm just not clear on what the problem is.

Every time you add a word to the User Dictionary, it will modify the VS Code `settings.json` file. That in turn will eventually get synced.

Please provide some more detail on the problem you are seeing and what you expect to happen instead.

**Comment by Jason3S** [comment]
Please reopen if this is still an issue.
