### ISSUE TITLE
extension stopped working

### ISSUE THREAD

**Issue by libussa** [streetsidesoftware/vscode-spell-checker#757]
I was running the extension for a while, and all of a sudden it stopped working.

- it's enabled, at the user and workspace level
- I see the filetype in the status bar, with a check mark next to it

But when I type text (with typos), it doesn't do anything anymore, no underline, nothing in the "problems" console.

I tried removing the extension entirely and re-installing, no change.

this is after a reinstall of the extension:
![image](https://user-images.githubusercontent.com/13407183/111353342-7f554880-8685-11eb-9bcb-6c270c2b7b05.png)

Any steps I can take to debug?

**Comment by Jason3S** [comment]
@libussa,

Thank you for bringing this up. It can be very frustrating when that happens. 

It is most likely related to the High CPU issues. Essentially, the extension gets stuck checking a file. It looks like it should be working, but nothing seems to happen.

We are working on a way to detect it and prevent it from happening.

High CPU Steps:

A few questions:
1. What kinds of files are you editing?
1. Would you provide a link to a repository so we can reproduce the issue?
1. Have you added any regular expressions to `ignoreRegExpList` or `includeRegExpList`?

From: https://github.com/streetsidesoftware/vscode-spell-checker/issues/393#issuecomment-586713148

In regular usage, this does not happen.

Common causes:
1. A runaway regex in the include / ignore section see [Runaway Regular Expressions: Catastrophic Backtracking](https://www.regular-expressions.info/catastrophic.html)
1. Incomplete install / update - this occasionally happens when VS Code installs / updates the extension. For some reason, it does not manage to download the entire extension and VS Code goes into a infinite loop trying to load the extension. The fix in this case is to uninstall the extension and to erase the cached copy from VS Code before reinstalling it.
1. A very large file - Add it to the `ignorePaths`.
1. Something else - this is where I need your help.

* Can you include a copy of your `cspell.json` file or the `cSpell.*` sections of the VS Code `settings.json` file.
* Please let me know the programming language and approximate size of the file.
* What OS are you using?
* Please include a copy of the VS Code About dialog.
* If you happen to have a public repository that exhibits this behavior, please send me a link.

See also: #650

**Comment by libussa** [comment]
> What kinds of files are you editing?

All kinds, but it stopped working while I was  on a medium python repo , I could see all errors in all files in the repo at the same time.  Testing now on `.md` and `.txt`

> Would you provide a link to a repository so we can reproduce the issue?

minimal example https://github.com/libussa/spellcheck-test

>  Have you added any regular expressions to ignoreRegExpList or includeRegExpList?

no

> Can you include a copy of your cspell.json file or the cSpell.* sections of the VS Code settings.json file.
```
{
    "version": "0.1",
    "import": [
        "../../cSpell.json"
    ],
    "enableFiletypes": [
        "literate haskell",
        "shellscript"
    ],
    "words": []
}
```

and all the cSpell.* settings:
```
    "cSpell.enabledLanguageIds": [
        "asciidoc",
        "c",
        "cpp",
        "csharp",
        "css",
        "git-commit",
        "go",
        "handlebars",
        "html",
        "jade",
        "java",
        "javascript",
        "javascriptreact",
        "json",
        "jsonc",
        "latex",
        "less",
        "markdown",
        "php",
        "pug",
        "python",
        "restructuredtext",
        "rust",
        "scala",
        "scss",
        "text",
        "typescript",
        "typescriptreact",
        "yaml",
        "yml"
    ],
    "cSpell.diagnosticLevel": "Hint",
    "cSpell.logLevel": "Debug",
    "cSpell.maxNumberOfProblems": 1000,
    "cSpell.enableFiletypes": [
        "plaintext"
    ],
    "cSpell.customFolderDictionaries": [
    
    ]
}
```

> Please let me know the programming language and approximate size of the file.

see example repo, very small file.

> What OS are you using?

ubuntu 20

> Please include a copy of the VS Code About dialog.

```
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:24.277Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-43-generic
```

**Comment by Jason3S** [comment]
@libussa,

Thank you.

## Something to try:

### VS Code with just the sample repo https://github.com/libussa/spellcheck-test

1. Quit VS Code.
2. Kill any `Code Helper` processes that might still be running.
3. From a terminal, `cd` to the example repo.
4. `code .` from the example repo.

Please let me know if it works.

## Other config files:

Would you please share: `../../cSpell.json`, that might include more information.

**Comment by bushong1** [comment]
Not OP, but I'm experiencing the same thing, and also running on Linux (Ubuntu 20.10)
Here are all my cSpell configs in settings.json
```
    "cSpell.enabled": true,
    "cSpell.language": "en,en-US",
    "cSpell.flagWords": [
        "verybadword"
    ]
```

**Comment by Jason3S** [comment]
It can stop working if you open a webpacked `.js` file. I'm working on a fix. If that is your case, add the file to the `ignorePaths` section of the configuration to prevent the spell checker from checking the file.

**Comment by bushong1** [comment]
I'm also opening a directory that has only a single, short markdown file with some typos.  I also added a flagWord `verybadword` and put that in, but it still said the file was okay.

**Comment by Jason3S** [comment]
@bushong1, 

Did you try quitting VS Code?
If that works, then the extension got stuck on another file.
