### ISSUE TITLE
code-spell-checker-2.0.0-alpha.3: Buffer() is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by vikivivi** [streetsidesoftware/vscode-spell-checker#870]
While installing code-spell-checker-2.0.0-alpha.3, I notice the following warning.
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

```sh
host$ unzip code-spell-checker.zip
host$ code --install-extension build/code-spell-checker-2.0.0-alpha.3.vsix 
Installing extensions...
(node:18487) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'code-spell-checker-2.0.0-alpha.3.vsix' was successfully installed.
```

**Comment by Jason3S** [comment]
This seems to be caused by  VS Code's Extension Host.

![image](https://user-images.githubusercontent.com/3740137/118452342-56d5e300-b6f6-11eb-9132-0ace5a2a4314.png)

See:
- [(node:1412) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. · Issue #93177 · microsoft/vscode](https://github.com/microsoft/vscode/issues/93177)
- [DeprecationWarning: Buffer() is deprecated due to security and usability issues · Issue #3331 · MicrosoftDocs/live-share](https://github.com/MicrosoftDocs/live-share/issues/3331)
