### ISSUE TITLE
add option to disable highlight in scrollbar

### ISSUE THREAD

**Issue by MrEmanuel** [streetsidesoftware/vscode-spell-checker#872]
I like this extension but the blue boxes in the scrollbar that mark spelling errors are getting in the way of other indicators such as selected strings/symbols and search hits. 

I have currently disabled the extension because of this. I looked for a way to turn off the highlighting in the scrollbar but couldn't find any setting. 

Hope you appreciate the feedback. Thanks for an otherwise great extension!

**Comment by Jason3S** [comment]
Thank you for the feedback. I can see how it is an issue. This is related to #504 and #272. There is not much we can do about it other than to raise the issue with VS Code. This extension uses the standard `Diagnostic` settings.

One possible work around would be to toggle the spell checker on / off.

![image](https://user-images.githubusercontent.com/3740137/118474849-d02c0080-b70b-11eb-83e6-e60f42942c94.png)

**Comment by Jason3S** [comment]
Another option is to set the `Diagnostic Level` to `hint`:

![image](https://user-images.githubusercontent.com/3740137/119503360-2c75cc80-bd6b-11eb-9047-3e93c25ef58a.png)

This will effectively hide it from both the problems list and from the scrollbar.

But it will look different `...` instead of `~~~`

![image](https://user-images.githubusercontent.com/3740137/119503598-71016800-bd6b-11eb-86e0-b735c66a20c7.png)

See: [VS Code: enable inline spell checker, but disable spell check in the "Problems" panel - Stack Overflow](https://stackoverflow.com/questions/50309834/vs-code-enable-inline-spell-checker-but-disable-spell-check-in-the-problems)

**Comment by Jason3S** [comment]
I'm closing this issue for now since there is not much that can be done at this moment.
