### ISSUE TITLE
How to ignore Dart Regular Express strings?

### ISSUE THREAD

**Issue by tjx666** [streetsidesoftware/vscode-spell-checker#918]
Versions:

```
Version: 1.57.0-insider (Universal)
Commit: 20df87725d3ce4a501187f0240c2f159aa0ad2a5
Date: 2021-06-03T06:00:36.788Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
Code Spell Checker: v1.10.2
```

![image](https://user-images.githubusercontent.com/41773861/120611407-bc5ff880-c486-11eb-9e52-4a9d2a23278f.png)

**Comment by Jason3S** [comment]
It is possible to tell the spell checker to ignore Dart regular expressions or just the `r'`.

Add the following to a `cspell.json` file:

```js
"languageSettings": [
    {
        "languageId": "dart",
        "patterns": [
            {
                "name": "Dart-RegExp-String",
                "pattern": "/\\br(['\"]).*?\\1/g"
            }
        ],
        "ignoreRegExpList": [
            "Dart-RegExp-String"
        ]
    }
]
```

Or you can add it to your VS Code settings using `cSpell.languageSettings` instead of `languageSettings`

To just ignore the `r'`, change the `pattern` to be `/\\br'/g`
