### ISSUE TITLE
Markdown: Checks code but not normal text

### ISSUE THREAD

**Issue by celynw** [streetsidesoftware/vscode-spell-checker#935]
For some reason, for me, only text in code blocks and inline code is checked by `cSpell`.

![example](https://user-images.githubusercontent.com/3299161/121335231-4f2ee600-c912-11eb-9747-a3b2084304b9.png)

Seems to not make a difference if this is a saved file or an untitled document.
I couldn't see anything obvious in the extension settings, maybe I missed something.
I also couldn't find a related issue.

- VSCode version: 1.56.2
- Extension version: 1.10.2
- There is a tick on the status bar for `cSpell` with markdown

**Comment by Jason3S** [comment]
This is mostly cause by `includeRegExpList` setting.

![image](https://user-images.githubusercontent.com/3740137/121356747-70eb9580-c931-11eb-89df-d7d0f4743d4d.png)

It might be something like: `"includeRegExpList": ["string"]`

In either the VS Code settings under `cSpell.includeRegExpList` or in a `cspell.json` file.

**Comment by lifekaizen** [comment]
> I wanted to set this only for markdown

I was also hoping to have spell check work for code within a markdown document. For example, use `mkdir` in a code snippet and _not_ have it show as misspelled. 

> It might be something like: `"includeRegExpList": ["string"]`
> In either the VS Code settings under `cSpell.includeRegExpList` or in a `cspell.json` file.

I tried this but the result does not seem correct. So I did some testing of the various conditions, including a [python file since I found `mkdir` in that dictionary](https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/python/python.txt). Here is what I found:


For a .md file using `"cSpell.includeRegExpList": []` 
- for a word in the python dictionary:
    - text is correct
    - code is NOT correct
    - code block is correct
- for a word not in english dictionary:
    - text is correct
    - code is correct
    - code block is NOT correct
- for a word in english dictionary:
    - code is correct
    - string is correct
    - code block is correct

           
<img width="396" alt="md none" src="https://user-images.githubusercontent.com/7156025/121430596-27994700-c92d-11eb-8b1d-ac63624180ae.png">


For a .md file using `"cSpell.includeRegExpList": ["string"]`:
- for a word in the python dictionary:
    - text is NOT correct
    - code is NOT correct
    - code block is NOT correct
- for a word not in english dictionary:
    - text is NOT correct
    - code is correct
    - code block is correct
- for a word in english dictionary:
    - code is correct
    - string is correct
    - code block is correct

<img width="400" alt="md string" src="https://user-images.githubusercontent.com/7156025/121430621-2ec05500-c92d-11eb-82cd-5c537bad65f7.png">


For a `.py` file using `"cSpell.includeRegExpList": []`:
- for a word in the python dictionary:
    - code is correct
    - string is correct
- for a word not in english dictionary:
    - code is correct
    - string is correct
- for a word not in english dictionary:
    - code is correct
    - string is correct

<img width="406" alt="py none" src="https://user-images.githubusercontent.com/7156025/121430648-34b63600-c92d-11eb-834f-6e32ebaf7cf1.png">

For a `.py` file using `"cSpell.includeRegExpList": ["string]`:
    - for a word in the python dictionary:
        - code is correct
        - string is correct
    - for a word not in english dictionary:
        - code is NOT correct
        - string is correct
    - for a word in english dictionary:
        - code is correct
        - string is correct


<img width="367" alt="py string" src="https://user-images.githubusercontent.com/7156025/121430663-3a138080-c92d-11eb-9b5f-ba9a65010b98.png">


I'm willing to try to help solve the issue, but not sure where to go from here. Perhaps the [creation of a markdown dictionary](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries) would help? Or maybe I'm doing something wrong?

**Comment by Jason3S** [comment]
@celynw 

> Is this a feature which can be added to this extension, or a limitation of VSCode?
Yes it is. But the spell checker has a way around it.

I guessing something like this is in your VS Code config:
```js
"cSpell.includeRegExpList": [
    "string"
],
```

It tells the spell check to only check strings in ALL languages.

To override it, there are two options

## Option 1 - languageSettings
Use the language settings to tell the spell checker to check Everything for `markdown`
```js
"cSpell.languageSettings": [
    {
        "languageId": "markdown",
        "includeRegExpList": ["Everything"]
    }
]
```

## Option 2 - filename based overrides
Use the overrides to change the config for all matching files.

```js
"cSpell.overrides": [
    {
        "filename": "*.md",
        "includeRegExpList": ["Everything"]
    }
]
```

**Comment by Jason3S** [comment]
@lifekaizen,

The purpose of `includeRegExpList` is to define which parts of the document need to be checked. By default the entire document is checked. `includeRegExpList` can be use the limit spell checking to only strings or comments with the use of a regular expression. The the programming language dictionaries define a set of patterns that can be used. But they are not standardized.

To include the python dictionary in a markdown file, this will work:
```
<!--- cspell:dictionaries python --->
```

![image](https://user-images.githubusercontent.com/3740137/121515597-a6ee4f80-c9ed-11eb-8c7d-6a3181c854d8.png)

**Comment by celynw** [comment]
> ## Option 1 - languageSettings
> 
> Use the language settings to tell the spell checker to check Everything for `markdown`
> 
> ```js
> "cSpell.languageSettings": [
>     {
>         "languageId": "markdown",
>         "includeRegExpList": ["Everything"]
>     }
> ]
> ```

This is perfect, thank you. Even better, it's more flexible. I'll close the issue.
